### ISSUE TITLE
Proposed PRs in my fork

### ISSUE THREAD

**Issue by michaelmayer-hpe** [bcornec/Labs#20]
Bruno,

Because I was not able to create PRs directly against, I have created two PRs in my fork of this repo.

1. added a Table of Contents and some minor fixes to Docker/README.md
2. separate note on following the Docker workshop using "Docker for Windows".

Let me know if this is OK.

Regards

Michael

**Comment by bcornec** [comment]
I don't see your PR here. You need to go in your repo and make a "New pull request" but vs my repo, not yours (I see 2 PRs in your own repo). Thtaa should allow me to see them and approve ... or discuss more ;-)

**Comment by michaelmayer-hpe** [comment]
I tried to create a PR on your repo but didn't have permission to create one.

(Sent from mobile)

Regards

Michael

Michael Mayer

Technical Consultant

Ask me about HPE Pointnext



michael.mayer@hpe.com
+44 1234 567890  Office
+44 7909 936 780   Mobile

Bracknell, UK
hpe.com

Hewlett-Packard Limited | Registered Office: Cain Road, Bracknell, Berkshire RG12 1HN | Registered Number: 00690597 England | VAT number: GB 314 1496 79

This e-mail may contain confidential and/or legally privileged material for the sole use of the intended recipient. If you are not the intended recipient (or authorized to receive for the recipient) please contact the sender by reply e-mail and delete all copies of this message. If you are receiving this message internally within the Hewlett Packard Enterprise group of companies, you should consider the contents “CONFIDENTIAL”.

On 9 Mar 2017 1:57 am, Bruno Cornec <notifications@github.com> wrote:

I don't see your PR here. You need to go in your repo and make a "New pull request" but vs my repo, not yours (I see 2 PRs in your own repo). Thtaa should allow me to see them and approve ... or discuss more ;-)

**Comment by bcornec** [comment]
Now solved
